#java -jar -Dspring.profiles.active=Qa foo-1.0.jar
# h2 database
server:
  port: 8083
debug: false
spring:
  application:
    name: SpringBootMockitoTest
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

